### ISSUE TITLE
missing logo, favicon

### ISSUE THREAD

**Issue by samiam2013** [somethingsoftware/something.software#5]
Lots of places on the site are using a bad logo, @Mr-Bossman  still has it (or maybe just get it from git history). Also no favicon is generally just a bad look.

**Comment by samiam2013** [comment]
![soft](https://github.com/somethingsoftware/something.software/assets/12667172/7894e489-774d-4465-a72d-8201f4dd7604)

**Comment by Mr-Bossman** [comment]
Here is the XCF gimp project file.
[?soft.zip](https://github.com/somethingsoftware/something.software/files/14250999/soft.zip)
